### ISSUE TITLE
Build failing on cachyos kernel 7.2.0.1

### ISSUE THREAD

**Issue by jbbandos** [morrownr/mt76#94]
Hello,
The build of the module has started to fail for me with the last updates of cachyos kernel (7.2.0.1). Checking the logs, there are two missing identifiers:
```
mt7925/mcu.c:1915:36: error: use of undeclared identifier 'IEEE80211_EML_CAP_EMLSR_PADDING_DELAY'
 1915 |                   (ext_capa->eml_capabilities & (IEEE80211_EML_CAP_EMLSR_PADDING_DELAY |
      |                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mt7925/mcu.c:1916:7: error: use of undeclared identifier 'IEEE80211_EML_CAP_EMLSR_TRANSITION_DELAY'
 1916 |                                                 IEEE80211_EML_CAP_EMLSR_TRANSITION_DELAY));
      |   
```

Checking linux/ieee80211-eht.h, these definitions were renamed on [Commit 5858f5e
](https://github.com/torvalds/linux/commit/5858f5e1588fab66573d50c06dbcdd12830044ca)

I've edited mt7925/mcu.c to use IEEE80211_EML_CAP_EML_PADDING_DELAY and IEEE80211_EML_CAP_EML_TRANSITION_DELAY and the module now builds, and it works after a reboot.

ETA: "sanitized" (SSID removed) driver-check output
[mt76-diag.txt](https://github.com/user-attachments/files/31543604/mt76-diag.txt)

PS: the in-kernel mode works on 7.2.0.1, so this is more a case of me wanting to use the "latest and greatest" code and firmware.

**Comment by Lucid-Duck** [comment]
@jbbandos Thanks for the report, and for tracking it back to the rename yourself. That is the whole diagnosis.

This is already fixed here. A compat shim went in on 17 July that picks the right names on either side of that commit, so main does not carry the identifiers you are hitting any more. Your clone is from before it.

A pull and a reinstall should be all it takes. Put `mt7925/mcu.c` back first with `git checkout -- mt7925/mcu.c`, or git will refuse to merge over your edit. You made the same change the fix did, so nothing is lost.

I built current main against 7.2 just now and every module comes up clean.

Nothing else in your diagnostic needs attention. I have the same card in this laptop and it is a quick one. Much speed. Very bandwidth.

**Comment by jbbandos** [comment]
I had pulled main before, and tried again now:
```
$ git pull
remote: Enumerating objects: 20, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 20 (delta 13), reused 18 (delta 13), pack-reused 0 (from 0)
Unpacking objects: 100% (20/20), 8.92 KiB | 702.00 KiB/s, done.
From https://github.com/morrownr/mt76
   bca9ca39..c436c7b6  main       -> origin/main
Already up to date.
```
So I dug a bit and found that the EML shim commit ([Commit 8b97f4a ](https://github.com/morrownr/mt76/commit/8b97f4ab134cb933487a229a92a0eceb92b9054c), I think) wasn't done on the main branch. 

The EML shim commit created branch [fix-mt7925-eml-rename-7.2](https://github.com/morrownr/mt76/compare/fix-mt7925-eml-rename-7.2)  and was never merged back to main. I didn't find it until I saw your comment.

You do have several branches that were created by a single commit and never merged back, is that on purpose?

**Comment by Lucid-Duck** [comment]
@jbbandos You are not on main. That output is what a pull prints from any other branch: it updates origin/main and leaves your own branch alone. `git branch --show-current` will say which one you are on.

Watch for your `mcu.c` edit when you switch. The checkout will refuse over it, since that file differs between the two.

The fix is on main. That branch belonged to a pull request that was squash-merged, so main got a new commit under a different id and the branch stayed behind looking unmerged. The shim itself is identical in both.

Thank you for pasting the full pull output. The answer was in it.

**Comment by jbbandos** [comment]
Sorry, I was really on the wrong branch for some time now.
```
$ git branch --show-current
series/mt7927-v5-1085548
```
Switched, pulled, and of course now it built. My apologies for wasting your time.
/me going back to reading up on how to use git...

**Comment by Lucid-Duck** [comment]
@jbbandos No worries at all. That branch is a stale one from April that should not still be sitting there, and you are also the one who spotted that the others look like unmerged work. Both are getting sorted out shortly, thanks again.
